kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs-data
spec:
  #storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
