apiVersion: v1
kind: PersistentVolume
metadata: 
  name: pv-nginx
  labels:
     type: local
spec:
  storageClassName: managed-nfs-storage
  capacity:
     storage: 2Gi
  accessModes:
     - ReadWriteMany
  nfs:
    server: 172.235.18.212
    path: "/srv/nginx"
