apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: pvc-nginx
spec:
   storageClassName: managed-nfs-storage
   accessModes:
        - ReadWriteMany
   resources:
     requests:
         storage: 2Gi
