apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
      - name: loki
        image: grafana/loki:latest
        args:
          - -config.file=/etc/loki/loki-config.yaml
        ports:
        - containerPort: 3100
        volumeMounts:
        - name: config
          mountPath: /etc/loki/
        - name: storage
          mountPath: /data/loki
 
      volumes:
      - name: config
        configMap:
          name: loki-cm
      - name: storage
        persistentVolumeClaim:
            claimName: test-claim-loki


---

apiVersion: v1
kind: Service
metadata:
  name: loki
spec:
  type: NodePort
  ports:
    - port: 3100
      targetPort: 3100
      nodePort: 31001
  selector:
    app: loki 
