apiVersion: apps/v1
kind: Deployment
metadata:
  name: collabora
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collabora
  template:
    metadata:
      labels:
        app: collabora
    spec:
      containers:
        - name: collabora
          image: collabora/code:latest
          ports:
            - containerPort: 9980
          env:
            - name: "domain"
              value: "pjdevops.com"
            - name: "server_name"
              value: "pjdevops.com"
            - name: "dictionaries"
              value: "de en es it"
            - name: "extra_params"
              value: "--o:ssl.enable=true --o:ssl.termination=true"
          securityContext:
            capabilities:
              add:
                - MKNOD
                - SYS_ADMIN
---
apiVersion: v1
kind: Service
metadata:
  name: collabora-service
spec:
  selector:
    app: collabora
  ports:
    - protocol: TCP
      port: 9980
      targetPort: 9980
      nodePort: 30080
  type: NodePort

