apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
spec:
  replicas: 1  # You can scale it as needed
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
        - name: nextcloud
          image: nextcloud:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nextcloud-storage
              mountPath: /var/www/html  # Path where Nextcloud stores data
      volumes:
        - name: nextcloud-storage
          hostPath:
            path: /mnt/data/nextcloud  # Host path where data will be stored on the node
            type: DirectoryOrCreate  # Creates the directory if it doesn't exist

---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-service
spec:
  selector:
    app: nextcloud
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30126
  type: NodePort # Change this based on your requirement (e.g., NodePort)

